spring.application.name=film-managmentSis5
spring.datasource.url=jdbc:postgresql://localhost:5432/film_management_db
spring.datasource.username=postgres
spring.datasource.password=hoholein1566

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.example.film_managmentSis5=DEBUG