spring.application.name=feed-serviceSis6
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/social_feed_db
spring.datasource.username=postgres
spring.datasource.password=datebayo01399

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=feed-group

springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.example.feed_serviceSis6=DEBUG
logging.level.org.springframework.kafka=DEBUG