spring.application.name=post-serviceSis6

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/social_post_db
spring.datasource.username=postgres
spring.datasource.password=datebayo01399

# JPA + Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.example.postservice=DEBUG